### ISSUE TITLE
Profiles table

### ISSUE THREAD

**Issue by maxschram** [charleswcho/okbnb#1]
What is the difference between location and exactLocation?

**Comment by charleswcho** [comment]
I want to display a persons location on their profile but only "City, State, Country" and not the rest of their address which is going to be used for the Google maps api.  You're right though, I can just use location and exclude data from being displayed on the Profile.  Or should I restrict the data sent over on the server side (using jbuilder) checking if the profile is owned by the current user or not?

**Comment by maxschram** [comment]
You want to avoid duplicating data in your database because it can cause really unpredictable and difficult to solve bugs. I think your suggestion of just changing what the view layer (Jbuilder template) returns in the JSON response is a much better pattern.
